name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build_artifacts:
    name: Build Artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos:
          - linux
          - windows
          - darwin
        goarch:
          - amd64
          - arm64
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.24"
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Set Asset Path
        if: ${{ matrix.goos == 'windows' }}
        shell: bash
        run: echo "ASSET_PATH=./bin/sshttproxy-${{ matrix.goos }}-${{ matrix.goarch }}.exe" >> $GITHUB_ENV
      - name: Set Asset Path
        if: ${{ matrix.goos != 'windows' }}
        shell: bash
        run: echo "ASSET_PATH=./bin/sshttproxy-${{ matrix.goos }}-${{ matrix.goarch }}" >> $GITHUB_ENV
      - name: Build Client (${{ matrix.goos }}-${{ matrix.goarch }})
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: go build -v -o ${{ env.ASSET_PATH }} ./cmd/proxy/main.go
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.ASSET_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
